### PR TITLE
Add automated deployment via Dockerfile, gh actions, k8s

### PR DESCRIPTION
**Pull request by jberger**
This can be a starting point for CI/CD and even k8s deployment

### CODE REVIEW

**Comment by jberger** [comment]
Calling for a vote @mojolicious/maintainers

**Comment by jberger** [comment]
You can see this work by looking at https://github.com/jberger/mojolicious.org/actions

**Comment by jberger** [comment]
For the record, merging this PR doesn't affect anything that is currently in use and would have no effect should it not work ... which it should.

**Review by marcusramberg — APPROVED** [review]
lgtm 👍

**Review by jhthorsen — APPROVED** [review]
Based on @jberger's reasoning (on IRC) I decide to approve this PR.

**Pull request merged**
